### PR TITLE
Bump Evidence to v14

### PR DESCRIPTION
**Pull request by aaronsteers**
Note:

There's a known issue with Evidence 14.0 related to build-strict not working:

- https://github.com/evidence-dev/evidence/issues/682

Codespace testing URL: https://github.com/codespaces/new?hide_repo_select=true&ref=bump-evidence-to-v14&repo=612676159

### CODE REVIEW

**Comment by gwenwindflower** [comment]
@aaronsteers running into some issues with either port forwarding or something else going on with this branch in Codespaces. i'm going to loop back around tomorrow morning with a fresher brain.

but in general i dig what's happening here, and once i can confirm it's working for Codespaces will get it in. 🙏🏻

**Comment by aaronsteers** [comment]
@gwenwindflower - No rush at all. I actually ran into problems with the port not being accessible when using Codespaces also, then switched to local development for that reason. Sorry for not raising it in the PR description - I made the switch early on and then forgot to loop back and retest.

I wonder if this is a break related to v14, perhaps related to the Svelte version bump. 

Perhaps someone else ran into something similar and opened an issue on the Evidence side. 

Probably worth holding off on merging this PR until the port issue is resolved. I am considering if it's worth reverting the version bump on my other PRs, but the DuckDB file versions are not compatible. So downgrading Evidence would cascade into me also needing to downgrade DuckDB in other places as well. 😬🤦‍♂️

**Comment by aaronsteers** [comment]
Opened:

- https://github.com/evidence-dev/evidence/issues/690

**Comment by hughess** [comment]
We're working through our v14 issues now! Hoping to have some fixes soon

I like the changes to the Evidence readme. One other thing we can do to remove a step in the process is add the `npm install` command to the codespaces setup in `.devcontainer/devcontainer.json`:

```json
"postCreateCommand": "python -m pip install --user -r requirements.txt && dbt deps && npm --prefix ./reports install",
```

With that, we can get the startup commands down to:
```shell
cd reports
npm run dev
```

**Comment by aaronsteers** [comment]
@gwenwindflower - Issue https://github.com/evidence-dev/evidence/issues/690 resolved and the updated `package.json` file in this PR should give the proper behavior.

👍 

Also, I updated this branch with the latest from main and cleaned up some of the excess file changes in the diff.

To my knowledge, my only last concern is https://github.com/evidence-dev/evidence/issues/682 (build:strict command).

**Comment by gwenwindflower** [comment]
@aaronsteers ayyyy awesome!

**Review by gwenwindflower — APPROVED** [review]

**Pull request merged**
